[versions]
net-kyori-indra = "3.1.3"
com-gradleup-shadow = "8.3.5"

ca-stellardrift-stylecheck = "0.2.1"
org-jspecify = "1.0.0"
org-jetbrains-annotations = "26.0.2"

org-junit = "5.11.4"


[libraries]
# build logic
indra-common = { group = "net.kyori", name = "indra-common", version.ref = "net-kyori-indra" }
indra-licenseHeader = { group = "net.kyori", name = "indra-licenser-spotless", version.ref = "net-kyori-indra" }
shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "com-gradleup-shadow" }

# development tools (code quality, annotations)
stylecheck = { group = "ca.stellardrift", name = "stylecheck", version.ref = "ca-stellardrift-stylecheck" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "org-jspecify" }
junit-jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "org-junit" }
junit-jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "org-junit" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "org-jetbrains-annotations" }

# libraries
