name: Publish
on:
    push:
        branches: [ "trunk" ]
        tags: [ "v**" ]
    release:
        types: [ published ]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -   name: "checkout git repository"
                uses: actions/checkout@v4
            -   name: "set execute permission for gradle wrapper"
                run: chmod +x ./gradlew
            -   name: "validate gradle wrapper"
                uses: gradle/actions/wrapper-validation@v4
            -   name: "setup jdk"
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: "21"
            -   name: "setup gradle"
                uses: gradle/actions/setup-gradle@v4
            -   name: "determine snapshot status"
                run: |
                    if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
                      echo "STATUS=snapshot" >> $GITHUB_ENV
                    else
                      echo "STATUS=release" >> $GITHUB_ENV
                    fi
            -   name: "publish to snapshots"
                if: "${{ env.STATUS != 'release' && github.event_name == 'push' && github.ref == 'refs/heads/trunk' }}"
                run: ./gradlew build publishAllPublicationsToKokirigladeSnapshotsRepository
                env:
                    MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
                    MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
            -   name: "publish to releases"
                if: "${{ env.STATUS == 'release' && github.event_name == 'release' }}"
                run: ./gradlew build publishAllPublicationsToKokirigladeReleasesRepository
                env:
                    MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
                    MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
